device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
data_root: 'data/'

dataset: 'cifar10'
num_classes: 
input_height: 
input_width:
input_channel:

# epochs: 100
eval_batch_size: 256
num_workers: 4
# lr: 0.01

# poison_rate: 0.1
# target_type: 'all2one'
# target_label: 0

model: 'preactresnet18'
random_seed: 0
index: 

# ratio: 0.05
ft_n_clean: 2500
ft_batch_size: 512
ft_lr_scheduler: linear
ft_lr: 0.0005
ft_reg_coeff: 0.5 
ft_temp: 2.0
ft_epochs: 50

